// Generated by gencpp from file Laika_ROS/LaikaAction.msg
// DO NOT EDIT!


#ifndef LAIKA_ROS_MESSAGE_LAIKAACTION_H
#define LAIKA_ROS_MESSAGE_LAIKAACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace Laika_ROS
{
template <class ContainerAllocator>
struct LaikaAction_
{
  typedef LaikaAction_<ContainerAllocator> Type;

  LaikaAction_()
    : header()
    , actions()  {
    }
  LaikaAction_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , actions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actions_type;
  _actions_type actions;




  typedef boost::shared_ptr< ::Laika_ROS::LaikaAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Laika_ROS::LaikaAction_<ContainerAllocator> const> ConstPtr;

}; // struct LaikaAction_

typedef ::Laika_ROS::LaikaAction_<std::allocator<void> > LaikaAction;

typedef boost::shared_ptr< ::Laika_ROS::LaikaAction > LaikaActionPtr;
typedef boost::shared_ptr< ::Laika_ROS::LaikaAction const> LaikaActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Laika_ROS::LaikaAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Laika_ROS::LaikaAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Laika_ROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'Laika_ROS': ['/home/edward/gps-spine/src/Laika/src/Laika_ROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Laika_ROS::LaikaAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Laika_ROS::LaikaAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Laika_ROS::LaikaAction_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d3cd45f80f16d72487ecd17a073e278";
  }

  static const char* value(const ::Laika_ROS::LaikaAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d3cd45f80f16d72ULL;
  static const uint64_t static_value2 = 0x487ecd17a073e278ULL;
};

template<class ContainerAllocator>
struct DataType< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Laika_ROS/LaikaAction";
  }

  static const char* value(const ::Laika_ROS::LaikaAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] actions\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::Laika_ROS::LaikaAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaikaAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Laika_ROS::LaikaAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Laika_ROS::LaikaAction_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAIKA_ROS_MESSAGE_LAIKAACTION_H
